name: Build and Deploy to S3

on:
  push:
    branches:
      - main  # Deploys when the main branch is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Build application
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }} # Example environment variable
      run: |
        yarn
        yarn build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Sync build to S3
      run: |
        aws s3 sync ./dist s3://buckethahaha --delete

    # # Optional: Invalidate CloudFront cache (if using CloudFront)
    # - name: Invalidate CloudFront cache
    #   if: always()
    #   run: |
    #     aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}